[theme]
base = "light"
primaryColor = "#1f77b4"

[server]
headless = true
enableCORS = false
port = 8501

[runner]
magicEnabled = true
installTracer = false
fixMatplotlib = true

[logger]
level = "info"

[client]
toolbarMode = "minimal"

# Configuraciones específicas para NLTK
[nltk]
# Variables de entorno para NLTK en Streamlit Cloud
# Estas se configuran automáticamente por el script de inicialización
